os:
  - linux

language: rust

addons:
  apt:
    packages:
      - cmake

rust:
- nightly

before_install:
  - sudo apt-get install -y libcairo2-dev

script:
  - cargo update
  - cargo build
  - cargo test
