os: linux
dist: bionic

language: rust
cache: cargo

addons:
  apt:
    update: true
    packages:
      - cmake
      - clang-10
      - lldb-10
      - lld-10
      - libc++-10-dev
      - libc++abi-10-dev

script:
  - cargo update
  - cargo build --release
  - cargo test
